### ISSUE TITLE
Public API is down

### ISSUE THREAD

**Issue by ghost** [evilarceus/Spotify-PlayCount#6]
```
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/home/evilarceus/dev/Spotify-PlayCount/node_modules/ws/lib/websocket.js:329:19)
    at WebSocket.ws.json (/home/evilarceus/dev/Spotify-PlayCount/app.js:83:42)
    at app.get (/home/evilarceus/dev/Spotify-PlayCount/app.js:47:12)
    at Layer.handle [as handle_request] (/home/evilarceus/dev/Spotify-PlayCount/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/evilarceus/dev/Spotify-PlayCount/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/evilarceus/dev/Spotify-PlayCount/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/evilarceus/dev/Spotify-PlayCount/node_modules/express/lib/router/layer.js:95:5)
    at /home/evilarceus/dev/Spotify-PlayCount/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/evilarceus/dev/Spotify-PlayCount/node_modules/express/lib/router/index.js:335:12)
    at next (/home/evilarceus/dev/Spotify-PlayCount/node_modules/express/lib/router/index.js:275:10)
```

**Comment by entriphy** [comment]
It's back up now. Server overheated due to some other program.
